username = "shared_user"
dbname = "shared_db"

[queries]
current_time = "SELECT NOW();"
create_table = "CREATE TABLE IF NOT EXISTS test (id SERIAL PRIMARY KEY, name TEXT);"
insert_example = "INSERT INTO test (name) VALUES ('example');"
fetch_all = "SELECT * FROM test;"
